steps:
    # Build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-crud', '.']
    # Push the Docker image to Google Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/go-crud']
    # Deploy the Docker image to Cloud Run with environment variables
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          - 'run'
          - 'deploy'
          - 'go-crud'
          - '--image'
          - 'gcr.io/$PROJECT_ID/go-crud'
          - '--platform'
          - 'managed'
          - '--region'
          - 'us-central1'
          - '--allow-unauthenticated'
          - '--set-env-vars DB_USERNAME=root,DB_PASSWORD=,DB_HOST=35.226.15.21,DB_PORT=3306,DB_NAME=golang_rest_api,SECRET=ayam12

